### ISSUE TITLE
are here some runtime dependencies needed to be installed before running llama-box rebuild windows amd64 release binary file(llama-box.exe) on a clean windows env?

### ISSUE THREAD

**Issue by shenliqing** [gpustack/llama-box#10]
System: Win10-amd64-21H1 AVX2 is enabled
vc runtime env Installed: Microsoft Visual C++ 2015-2019 Redistributable(x64)-14.29.30139 
download & unzip & run  llama-box rebuild windows amd64 release binary llama-box-windows-amd64-avx2.zip -> llama-box.exe

shell just get a empty line output and exit:
``` 
C:\llama-box>llama-box.exe -h

C:\llama-box>
```

```
Window log viewer has an application error message

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-14T01:14:30.9476968Z" />
    <EventRecordID>782</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>ADMIN9922</Computer>
    <Security />
  </System>
  <EventData>
    <Data>llama-box.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>674fb3c7</Data>
    <Data>MSVCP140.dll</Data>
    <Data>14.29.30139.0</Data>
    <Data>61b17c25</Data>
    <Data>c0000005</Data>
    <Data>0000000000013020</Data>
    <Data>1758</Data>
    <Data>01db4dc58728aeef</Data>
    <Data>C:\llama-box\llama-box.exe</Data>
    <Data>C:\Windows\SYSTEM32\MSVCP140.dll</Data>
    <Data>1d667bcf-52a3-4ddc-b757-6f1d10250424</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

are here some runtime dependencies needed to be installed before running llama-box rebuild windows amd64 release binary file(llama-box.exe) on a clean windows env?

**Comment by thxCode** [comment]
have you try `./llama-box.exe -h`?

**Comment by shenliqing** [comment]
yes, i retried, it is `.\llama-box.exe -h` on windows and it needn't in windows command shell normally. only output a empty line in command shell.

**Comment by thxCode** [comment]
@shenliqing so it works for you?

**Comment by shenliqing** [comment]
not works yet.
my error is https://github.com/gpustack/llama-box/releases/download/v0.0.93/llama-box-linux-amd64-avx2.zip can not run alone on a clean win 10 (versions: 21h1 and 22h2) / win11 systems which is not installed  whole gpustack app.

**Comment by shenliqing** [comment]
Hi, i have finded the runtime dependency for running llama-box rebuild windows amd64 release binary( llama-box-windows-amd64-avx2.zip / llama-box.exe) alone : 

it need the "Visual C++ Redistributable for Visual Studio 2015-2022" be installed.

my env is Microsoft Visual C++ 2015-2019 Redistributable(x64) and `.\llama-box.exe -h` cant not work.

when i installed "Visual C++ Redistributable for Visual Studio 2015-2022", `.\llama-box.exe -h` can work correctly.

**Comment by shenliqing** [comment]
Thank you for the reply and concern, maybe pre-build llama-box.exe with vc++ runtime static compile option is a good way to use llama-box.exe in any win10 env as a portable exe.

**Comment by shenliqing** [comment]
Thank you for the reply and concern, maybe pre-build llama-box.exe with vc++ runtime static compile option is a good way to use llama-box.exe in any win10 env as a portable exe.
