### ISSUE TITLE
Support status of vision models

### ISSUE THREAD

**Issue by shibingli** [gpustack/llama-box#9]
Do vision models only support LLaVA-Phi-3-Mini? Do they support llava-v1.6-vicuna, llava-v1.6-mistral, llava-v1.5-13b, llava-v1.6-34b, and MiniCPM-V-2_6?

**Comment by thxCode** [comment]
for llama-box, I think minicpm-v-2_6 is not supported well at present, minicpm needs a specific prompt prefix rather than llava: https://github.com/ggerganov/llama.cpp/blob/86dc11c5bcf34db2749d8bd8d4fa07a542c94f84/examples/llava/minicpmv-cli.cpp#L217-L241. 

have you tried other models? I'm glad to see your feedback here.

**Comment by thxCode** [comment]
@shibingli v0.0.89 should support LLaVA 1.5 (and its variants), MiniCPM-V-2.5, MiniCPM-V-2.6. LLaVA 1.6 (and its variants) still not work as expected at present, I will keep this issue until I figure it out.

**Comment by thxCode** [comment]
LLaVA 1.5
```
llama-box -c 16384 -np 4 --host 0.0.0.0 -m second-state/Llava-v1.5-7B-GGUF/llava-v1.5-7b-Q4_0.gguf --mmproj second-state/Llava-v1.5-7B-GGUF/llava-v1.5-7b-mmproj-model-f16.gguf --chat-template llava
```

LLaVA 1.5 variant
```
llama-box -c 16384 -np 4 --host 0.0.0.0 -m xtuner/llava-phi-3-mini-gguf/llava-phi-3-mini-f16.gguf --mmproj xtuner/llava-phi-3-mini-gguf/llava-phi-3-mini-mmproj-f16.gguf
```

MiniCPM V-2.5
```
llama-box -c 16384 -np 4 --host 0.0.0.0 -m openbmb/MiniCPM-Llama3-V-2_5-gguf/ggml-model-Q4_0.gguf --mmproj openbmb/MiniCPM-Llama3-V-2_5-gguf/mmproj-model-f16_for_pr.gguf
```

MiniCPM V2-6
```
llama-box -c 16384 -np 4 --host 0.0.0.0 -m lmstudio-community/MiniCPM-V-2_6-GGUF/MiniCPM-V-2_6-Q4_K_M.gguf --mmproj lmstudio-community/MiniCPM-V-2_6-GGUF/mmproj-model-f16.gguf
```

**Comment by thxCode** [comment]
@shibingli  v0.0.90 should support LLaVA 1.6 (and its variants).

**Comment by thxCode** [comment]
LLaVA 1.6 7B
```
llama-box -c 16384 -np 4 --host 0.0.0.0 -m second-state/Llava-v1.6-Vicuna-7B-GGUF/llava-v1.6-vicuna-7b-Q4_0.gguf --mmproj second-state/Llava-v1.6-Vicuna-7B-GGUF/llava-v1.6-vicuna-7b-mmproj-model-f16.gguf --chat-template llava
```

LLaVA 1.6 7B variant
```
llama-box  -c 16384 -np 4 --host 0.0.0.0 -m mradermacher/llava-v1.6-mistral-7b-GGUF/llava-v1.6-mistral-7b.Q4_0.gguf --mmproj mradermacher/llava-v1.6-mistral-7b-GGUF/mmproj-model-f16.gguf [--chat-template llava-mistral]
```

LLaVA 1.6 34B
```
llama-box -c 16384 -np 4 --host 0.0.0.0 -m cjpais/llava-v1.6-34B-gguf/llava-1.6-34b.Q3_K_XS.gguf --mmproj cjpais/llava-v1.6-34B-gguf/mmproj-model-f16.gguf
```

**Comment by shibingli** [comment]
Cool, it's really great, thank you for the support!!!

**Comment by thxCode** [comment]
closed as completed
